### ISSUE TITLE
Pending deprecation for new Buffer()

### ISSUE THREAD

**Issue by sholladay** [hapijs/b64#15]
On Node 8...

```js
// my-app.js
require('b64');
```

```console
$ node --throw-deprecation --pending-deprecation my-app
internal/process/warning.js:151
        throw warning;
        ^

DeprecationWarning: The Buffer() and new Buffer() constructors are not recommended for use due to security and usability concerns. Please use the new Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() construction methods instead.
    at showFlaggedDeprecation (buffer.js:100:13)
    at new Buffer (buffer.js:121:3)
    at Object.<anonymous> (/Users/sholladay/sandbox/b64-test/node_modules/b64/lib/decoder.js:17:12)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
```

Obviously this does not have an immediate impact for most people given that these flags are uncommon outside of development. But just a heads up that [decoder.js#L17](https://github.com/hapijs/b64/blob/2daa533cc61b90ad06e5f4236e0377292b8cd88a/lib/decoder.js#L17) needs an update to use one of the more explicit Buffer construction methods.

**Comment by AdriVanHoudt** [comment]
are the new constructors supported in node 4?

**Comment by kanongil** [comment]
It seems that the fix should be simple in this case – just remove the line, as `internals.blank` is not even used.

**Comment by AdriVanHoudt** [comment]
@kanongil nice catch
